title: 'Nasrin Schneider Faszientherapie Hamburg-Harvestehude'
url: 'https://faszien-hamburg.de'
permalink: none
locale: de_DE
timezone: Europe/Berlin
defaults:
    -
        scope:
            path: ''
            type: pages
        values:
            layout: page
    -
        scope:
            path: ''
            type: therapies
        values:
            layout: therapy
    -
        scope:
            path: ''
            type: posts
        values:
            layout: blog_post
collections:
    therapies:
        output: true
        permalink: '/:path.html'
    testimonials:
        output: false
mediaurl: _media
assets:
    compress:
        css: false
        js: true
    digest: true
    sources:
        - bower_components
        - _assets/fonts
        - _assets/css
        - _assets/images
        - _assets/js
        - _media
baseurl: /
exclude:
    - 'Gemfile*'
    - 'bower*'
    - README.md
    - vendor
analytics:
    provider: google_analytics
    tracking_id: UA-86041858-1
comments:
    provider: facebook_comments
    num_posts: 0
    width: 0
sharing:
    limit: '3'
    provider:
        - facebook
        - twitter
        - google
        - pinterest
profiles:
    provider:
        - facebook
        - youtube
        - instagram
    facebook: 'https://www.facebook.com/FaszienNasrin'
    twitter: 'https://twitter.com/fasziennasrin'
    google: 'https://plus.google.com/114914002637307311681'
    linkedin: 'https://www.linkedin.com/in/nasrin-schneider-a8281886'
    youtube: 'https://www.youtube.com/channel/UCMpC3Fi-nCYj7hqL0ckDigQ'
    xing: 'https://www.xing.com/profile/Nasrin_Schneider'
    instagram: 'https://www.instagram.com/faszien_hamburg/?hl=de'
    pinterest: 'https://www.pinterest.de/FaszienNasrin/'
contact:
    location: 'Therapeutenzentrum Rotherbaum'
    address: "Alsterchaussee 3\r\n20149 Hamburg"
    telephone: '0176 9651 8194'
    email: info@faszien-hamburg.de
